#atenção: criar um arquivo settings.py apenas para os sprites do mapa
#talvez colocar os parâmetros do mapa nesse arquivo também


#screen and map settings
DELTA_GAME = 50
SCREEN_SIZE = (1200, 1000)
SCREEN_FULLSCREEN = False
ENDLESS_MODE = False
MAX_FLOOR = 10

BOSS_FLOOR = 8
BLOCK_SPEED = 1
BLOCK_SIZE = 60

CAMERA_SPEED = 0
SHOOT_SPEED = 2000
SPAWN_SPEED = 15000

#settings
PLAYER_SPAWN = (SCREEN_SIZE[0] // 2 + 200, SCREEN_SIZE[1] - 300)
PLAYER_INITIAL_NEXT_LEVEL = 100
PLAYER_LEVEL_MULTIPLIER = 0.2
PLAYER_SIZE = (25,25)
PLAYER_INITIAL_DAMAGE = 50
PLAYER_INITIAL_HEALTH = 1000
PLAYER_INITIAL_MAX_HEALTH = 1000
PLAYER_INITIAL_SPEED = 4
PLAYER_INITIAL_DASH = 0
PLAYER_INITIAL_SHOOT = 0
PLAYER_INITIAL_LS = 0

PLAYER_WEAPON_SIZE = (100, 80)


#enemies settings
ENEMY_FLOOR_MULTIPLIER = 0.2

WEAKMOV_SIZE = (25, 100)
WEAKMOV_INITIAL_HEALTH = 100
WEAKMOV_INITIAL_DAMAGE = 20
WEAKMOV_INITIAL_SPEED = 2
WEAKMOV_SIGHT_RADIUS = 200
WEAKMOV_XP = 20

STRMOV_SIZE = (50, 100)
STRMOV_INITIAL_HEALTH = 200
STRMOV_INITIAL_DAMAGE = 30
STRMOV_INITIAL_SPEED = 1
STRMOV_SIGHT_RADIUS = 200
STRMOV_XP = 40

SHOOT_SIZE = (50, 50)
SHOOT_INITIAL_HEALTH = 50
SHOOT_INITIAL_DAMAGE = 15
SHOOT_TIMER = 5
SHOOT_SIGHT_RADIUS = 600
SHOOT_XP = 30

BOSS_SHOOT_SIZE = (50, 50)
BOSS_SHOOT_INITIAL_HEALTH = 200
BOSS_SHOOT_INITIAL_DAMAGE = 30
BOSS_SHOOT_MAX_OFFSET = 2
BOSS_SHOOT_XP = 50

BOSS_SIZE = (100, 100)
BOSS_INITIAL_HEALTH = 1000
BOSS_INITIAL_MAX_HEALTH = 1000
BOSS_INITIAL_DAMAGE = 10
BOSS_MAX_OFFSET = 2
BOSS_ATTACK2_PROJECTS = 10
BOSS_XP = 1000


#buffs settings
NUMBER_BUFFS = 4

DAMAGE_EFFECT = 0.2
DAMAGE_PROB = 20

JUMP_EFFECT = 1
JUMP_PROB = 10

SHOOT_EFFECT = 1
SHOOT_PROB = 15

HEALTH_EFFECT = 0.1
HEALTH_PROB = 20

VEL_EFFECT = 0.1
VEL_PROB = 15

DASH_EFFECT = 1
DASH_PROB = 10

LS_EFFECT = 0.1
LS_PROB = 10

#sprites
PLAYER_WEAPON_SPRITE = "../../sprites/weapon.png"
PLAYER_IDLE_SPRITE = "../../sprites/idle.png"
PLAYER_RUN_SPRITE = "../../sprites/run.png"
PLAYER_BULLET_SPRITE = "../../sprites/1.png"

SHOOT_ENEMIES_BULLET_SPRITE = "../../sprites/1.png"
SHOOT_ENEMIES_IDLE_SPRITE = "../../sprites/Fire_Spirit/Idle.png"
SHOOT_ENEMIES_ATTACK_SPRITE = "../../sprites/Fire_Spirit/Shot.png"
SHOOT_ENEMIES_DEATH_SPRITE = "../../sprites/Fire_Spirit/Dead.png"

WEAKMOV_IDLE_SPRITE = "../../sprites/Skeleton/Idle.png"
WEAKMOV_ATTACK_SPRITE = "../../sprites/Skeleton/Attack_1.png"
WEAKMOV_DEATH_SPRITE = "../../sprites/Skeleton/Dead.png"
WEAKMOV_WALK_SPRITE = "../../sprites/Skeleton/Walk.png"

STRMOV_IDLE_SPRITE = "../../sprites/Plent/Idle.png"
STRMOV_ATTACK_SPRITE = "../../sprites/Plent/Attack_1.png"
STRMOV_DEATH_SPRITE = "../../sprites/Plent/Dead.png"
STRMOV_WALK_SPRITE = "../../sprites/Plent/Walk.png"

BOSS_BULLET_SPRITE = "../../sprites/1.png"
BOSS_SPRITES = None

DAMAGE_SPRITE = "../../sprites/buff.jpg"
JUMP_SPRITE = "../../sprites/buff.jpg"
SHOOT_SPRITE = "../../sprites/buff.jpg"
HEALTH_SPRITE = "../../sprites/buff.jpg"
VEL_SPRITE = "../../sprites/buff.jpg"
DASH_SPRITE = "../../sprites/buff.jpg"
LS_SPRITE = "../../sprites/buff.jpg"


KEY_SPRITE = "../../sprites/grass.png"